config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :jobs
  devise_for :admins , :jobs 
  get 'admins/'     => 'admins#index'
  get 'admins/job/' => 'admins#jobs'

  root 'jobs#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/job.rb
class Job < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Mount Uploader
  mount_uploader :avatar , AvatarUploader
  mount_uploader :cv , CvUploader 
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:job,:show, :edit, :update, :destroy]
  before_action :authenticate_admin! ,  only: [:index,:job,:show, :edit, :update, :destroy]
  # custom layout
  layout 'admin_layout'
  # GET /admins
  # GET /admins.json
  def index
    @admin = Admin.all
    @jobs  = Job.order(id: :desc).page params[:page]
  end
  # GET /admins/jobs
  def jobs
    @admin = Admin.all
    @jobs = Job.order(id: :desc).page params[:page]
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    @admin = :set_admin
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.fetch(:admin, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_admin!,:set_job, only: [ :new,:edit, :update, :destroy]
  before_action :set_job, only: [:show]
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.order(id: :desc).page params[:page]
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.fetch(:job, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,only: [:index,:new,:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit( :cv,:avatar,:title ,  :first_name ,  :last_name , :middle_name ,  :experience_time,  :skill_set , :about ,  :github_url , :linked_in_url , :personal_site, :date_birth, :month_birth, :year_birth)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<%= render 'partials/notice_alert' %>

app/views/admins/jobs.html.erb
<%= render "partials/admins/admin_job_list" %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-5 col-md-offset-4">
    <%= f.label  :title %>
    <%= f.text_field :title , :class => "form-control"%>

    <%= f.label  :description %>
    <%= f.text_area :description , :class => "form-control"%>

    <%= f.label  :company_name %>
    <%= f.text_field :company_name , :class => "form-control"%>

    <%= f.label  :company_address %>
    <%= f.text_field :company_address , :class => "form-control"%>

    <%= f.label  :location %>
    <%= f.text_field :location , :class => "form-control"%>

    <%= f.label  :salary %>
    <%= f.text_field :salary , :class => "form-control"%>

    <%= f.label  :postiion %>
    <%= f.text_field :postiion , :class => "form-control"%>


  </div>

  <br>
  <div class="actions">

    <%= f.submit "Save" , :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="text-center">
  <h4>Edit the <strong><%= @job.title %></strong></h4>
</div>

<%= render 'form' %>

<%= link_to 'Show', @job , :class => "btn btn-success" %>
<%= link_to 'Back', jobs_path , :class => "btn btn-default"%>

app/views/jobs/index.html.erb
<%= render "partials/notice_alert" %>


<%= render "partials/job_list_table" %>
<div class="col-md-offset-3">
  <%= paginate @jobs , :theme=> 'twitter-bootstrap-3' , :pagination_class => 'pagination-sm' %>
</div>


<!-- <%= link_to 'New Job', new_job_path %> -->

app/views/jobs/new.html.erb
<h4 class="text-center">Add New Job</h4>

<%= render 'form' %>
<br>
<%= link_to 'Back', jobs_path , :class => "btn btn-success" %>

app/views/jobs/show.html.erb
<%= render "partials/notice_alert" %>
<div class="container">
  <div class="row">
    <div class="panel panel-info col-md-6 col-md-offset-3">
      <div class="panel-heading">
        <h2 class="panel-title"><%= @job.title %>  at  <em><%= @job.company_name %></em></h2>
      </div>
      <div class="panel-body">
        <ul class="list-group">
          <li class="list-group-item">Position: <%= @job.postiion %></li>
          <li class="list-group-item">Description: <%= @job.description %></li>
          <li class="list-group-item">Salary: <%= @job.salary %></li>
          <li class="list-group-item">Work Location: <%= @job.location %></li>
          <li class="list-group-item">Company Address: <%= @job.company_address %></li>

        </ul>
      </div>
    </div>

    <% if(admin_signed_in?) %>
      <%= link_to 'Edit', edit_job_path(@job) , class: "btn btn-info" %> |
    <% end %>

  </div>

  <div class="row">
    <div class="col-md-3 col-md-offset-3">
      <%= link_to 'Back', jobs_path , class: "btn btn-default "%>
    </div>
  </div>
  
</div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeedRockstar</title>
  <%= stylesheet_link_tag    'admins', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'partials/admins/sidebar' %>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeedRockstar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "partials/navbar" %>
  
<%= yield %>

</body>
</html>

app/views/partials/_job_list_table.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-bordered table-condensed">
        <tr>
          <th>Title</th>
          <th>Postion</th>
          <th>Company Name</th>
          <th>Location</th>
          <th>Action</th>
        </tr>

          <% @jobs.each do |job| %>
          <tr>
          <td><%= job.title  %><%=job.id %> </td>
          <td><%= job.postiion %></td>
          <td><%= job.company_name %></td>
          <td><%= job.location %></td>
          <td>
            <%= link_to 'Show', job , class:"btn btn-info"%>
            <% if(admin_signed_in?) %>
              <%= link_to 'Edit', edit_job_path(job) , :class => "btn btn-primary" %>
              <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger"%>
            <% end %>
          </td>
          </tr>
          <% end %>

      </table>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Seed Rockstar</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="active"><%= link_to "Home" , "/" , span: "class:sr-only" %></li>
        <li><%= link_to "Jobs Listing" , '/jobs' %></li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
    </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if (!admin_signed_in?) %>
          <li><%= link_to "Login" , admins_path %></li>
        <% else %>
          <li><%= link_to "Admin" , admins_url  %></li>
          <li><%= link_to "Sign Out" , destroy_admin_session_path , :method => "delete" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_notice_alert.html.erb
<% if(notice)%>
  <p class="notice alert alert-info"><em><%= notice %></em></p>
<% end %>
<% if(alert) %>
  <p class="alert alert-info"><em><%= alert %></em></p>
<% end %>

app/views/partials/admins/_admin_job_list.html.erb
<div class="col-md-8 col-md-offset-2">
  <table class="table table-bordered table-condensed">
    <tr>
      <th>Title</th>
      <th>Postion</th>
      <th>Company Name</th>
      <th>Location</th>
      <th>Action</th>
    </tr>

      <% @jobs.each do |job| %>
      <tr>
      <td><%= job.title  %><%=job.id %> </td>
      <td><%= job.postiion %></td>
      <td><% job.company_name %></td>
      <td><%= job.location %></td>
      <td>
        <%= link_to 'Show', job , class:"btn btn-info"%>
        <% if(admin_signed_in?) %>
          <%= link_to 'Edit', edit_job_path(job) , :class => "btn btn-primary" %>
          <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger"%>
        <% end %>
      </td>
      </tr>
      <% end %>

  </table>
</div>

<div class="col-md-offset-3">
  <%= paginate @jobs , :theme=> 'twitter-bootstrap-3' , :pagination_class => 'pagination-sm' %>
</div>

app/views/partials/admins/_sidebar.html.erb
  <div id="wrapper">

      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to 'Seed Rockstar' , admins_path , class: "navbar-brand" %>

          </div>
          <!-- Top Menu Items -->
          <ul class="nav navbar-right top-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                  <ul class="dropdown-menu message-dropdown">
                      <li class="message-preview">
                          <a href="#">
                              <div class="media">
                                  <span class="pull-left">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="">
                                  </span>
                                  <div class="media-body">
                                      <h5 class="media-heading">
                                          <strong>John Smith</strong>
                                      </h5>
                                      <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                      <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="message-preview">
                          <a href="#">
                              <div class="media">
                                  <span class="pull-left">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="">
                                  </span>
                                  <div class="media-body">
                                      <h5 class="media-heading">
                                          <strong>John Smith</strong>
                                      </h5>
                                      <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                      <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="message-preview">
                          <a href="#">
                              <div class="media">
                                  <span class="pull-left">
                                      <img class="media-object" src="http://placehold.it/50x50" alt="">
                                  </span>
                                  <div class="media-body">
                                      <h5 class="media-heading">
                                          <strong>John Smith</strong>
                                      </h5>
                                      <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                      <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="message-footer">
                          <a href="#">Read All New Messages</a>
                      </li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                  <ul class="dropdown-menu alert-dropdown">
                      <li>
                          <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                      </li>
                      <li>
                          <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                      </li>
                      <li>
                          <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                      </li>
                      <li>
                          <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                      </li>
                      <li>
                          <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                      </li>
                      <li>
                          <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">View All</a>
                      </li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li>
                          <%= link_to jobs_path do %>
                            <i class="fa fa-fw fa-globe"></i> Visit Site
                          <% end %>
                      </li>
                      <li>
                          <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                      </li>

                      <li class="divider"></li>
                      <li>
                          <% if(admin_signed_in?) %>
                            <%= link_to  destroy_admin_session_path , :method => "delete" do%>
                                <i class="fa fa-fw fa-power-off"></i> Logout
                            <% end %>
                          <% end %>
                      </li>
                  </ul>
              </li>
          </ul>
          <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav side-nav">
                  <li>
                      <%= link_to admins_path do %>
                          <i class="fa fa-fw fa-dashboard"></i> Dashboard
                      <% end %>
                  </li>
                  <li>
                      <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Jobs <i class="fa fa-fw fa-caret-down"></i></a>
                      <ul id="demo" class="collapse">
                          <li>
                              <%= link_to "All Job List" , :controller => "admins" , :action =>"jobs" %>
                          </li>

                          <li>
                              <%= link_to "New Job Entry" , :controller => "jobs" , :action => "new" %>
                          </li>

                      </ul>
                  </li>
                  <li class="active">
                      <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
                  </li>

              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">

          <div class="container-fluid">

              <!-- Page Heading -->
              <div class="row">
                  <div class="col-lg-12">
                      <h1 class="page-header">
                          Admin Panel

                      </h1>
                      <ol class="breadcrumb">
                          <li>
                              <%= link_to admins_path , :class => "active" do %>
                                  <i class="fa fa-dashboard"></i> Dashboard
                              <% end %>
                          </li>
                          
                          <!-- <li class="active">
                              <i class="fa fa-file"></i> Blank Page

                          </li> -->
                      </ol>
                      <%= yield %>
                  </div>
              </div>
              <!-- /.row -->

          </div>
          <!-- /.container-fluid -->

      </div>
      <!-- /#page-wrapper -->

  </div>
  <!-- /#wrapper -->

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <li><%= user.title %> <%= user.first_name %></li>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render "partials/notice_alert" %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <%= image_tag @user.avatar_url,:class=>"img img-responsive img-round" if @user.avatar?  %>
        <h1 class="text-center lead"> <%= @user.first_name %> <%= @user.last_name %>  <small>[ Profile ]</small></h1>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Personal Information</h3>
            </div>
            <div class="panel-body">
              <ul class="list-group">
              <li class="list-group-item"><strong>Name:</strong> <%= @user.title %>. <%= @user.first_name %> <%= @user.last_name %></li>
              <li class="list-group-item"><strong>Date Of Birth:</strong> <%= @user.date_birth %>-<%= @user.month_birth %>-<%= @user.year_birth %></li>
              <li class="list-group-item"><strong>About Me:</strong> <%= @user.about %></li>
              <li class="list-group-item"><strong>Email:</strong> <%= @user.email %></li>
                <% if @user.personal_site %>
                  <li class="list-group-item"><strong>Personal Site: </strong> <%= @user.personal_site %></li>
                <% end %>
              </ul>

            </div>
          </div>

          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Skills of <%= @user.first_name %></h3>
            </div>
            <div class="panel-body">
              <ul class="list-group">
                <li class="list-group-item"><strong>Skill Set:</strong> <%= @user.skill_set %></li>
                <li class="list-group-item"><strong>Experience Time Period: </strong> <%= @user.experience_time %> Years</li>
                <li class="list-group-item"><strong>Github Link: </strong> <%= link_to @user.github_url , @user.github_url , target: '_blank'%></li>
                <li class="list-group-item"><strong>LinkedIn Url:</strong> <%= link_to @user.linked_in_url , @user.linked_in_url , target: '_blank' %></li>
                <li class="list-group-item"><strong>CV:</strong> <%= link_to "CV Link of #{@user.first_name}" , @user.cv_url , :target=>"_blank" , :class=> "btn btn-primary" %></li>
              </ul>

            </div>
          </div>


          <%= link_to 'Edit', edit_user_path(@user) , :class=>"btn btn-default" %>
          <%= link_to 'Back', users_path ,  :class=>"btn btn-info"%>

        </div>
      </div>
    </div>
  </div>
</div>